//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spider.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2015 Brian Holley.
        /// </summary>
        internal static string About_CopyrightInfo {
            get {
                return ResourceManager.GetString("About_CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program/Graphics.
        /// </summary>
        internal static string About_CopyrightLabel {
            get {
                return ResourceManager.GetString("About_CopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe Print.
        /// </summary>
        internal static string About_FontCopyrightInfo {
            get {
                return ResourceManager.GetString("About_FontCopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string About_FontCopyrightLabel {
            get {
                return ResourceManager.GetString("About_FontCopyrightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Spider.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Mode.
        /// </summary>
        internal static string About_TrialModeLabel {
            get {
                return ResourceManager.GetString("About_TrialModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to upgrade to the full version of Spider.
        /// </summary>
        internal static string About_UpgradeLabel {
            get {
                return ResourceManager.GetString("About_UpgradeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string About_VersionLabel {
            get {
                return ResourceManager.GetString("About_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires the
        ///full version of Spider.
        ///Click here to go
        ///to the Marketplace..
        /// </summary>
        internal static string DisabledInTrial {
            get {
                return ResourceManager.GetString("DisabledInTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deal a new row while there are empty stacks.
        /// </summary>
        internal static string EmptyStacksDealError {
            get {
                return ResourceManager.GetString("EmptyStacksDealError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Spider.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version.
        /// </summary>
        internal static string Menu_TrialBanner {
            get {
                return ResourceManager.GetString("Menu_TrialBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to go to the
        ///Marketplace to upgrade
        ///to the full version of Spider..
        /// </summary>
        internal static string Menu_TrialBannerNav {
            get {
                return ResourceManager.GetString("Menu_TrialBannerNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot currently reach
        ///the Marketplace.  Please
        ///try again later..
        /// </summary>
        internal static string Menu_TrialNavFailed {
            get {
                return ResourceManager.GetString("Menu_TrialNavFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Options_DarkTheme {
            get {
                return ResourceManager.GetString("Options_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck.
        /// </summary>
        internal static string Options_DeckColorLabel {
            get {
                return ResourceManager.GetString("Options_DeckColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        internal static string Options_ModernTheme {
            get {
                return ResourceManager.GetString("Options_ModernTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original.
        /// </summary>
        internal static string Options_OriginalTheme {
            get {
                return ResourceManager.GetString("Options_OriginalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Options_ThemeLabel {
            get {
                return ResourceManager.GetString("Options_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming Spider.
        /// </summary>
        internal static string Resuming {
            get {
                return ResourceManager.GetString("Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Won.
        /// </summary>
        internal static string Stats_GamesWon {
            get {
                return ResourceManager.GetString("Stats_GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Clear].
        /// </summary>
        internal static string Stats_ResetButton {
            get {
                return ResourceManager.GetString("Stats_ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        internal static string Stats_TotalGames {
            get {
                return ResourceManager.GetString("Stats_TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Played.
        /// </summary>
        internal static string Stats_TotalTimeLabel {
            get {
                return ResourceManager.GetString("Stats_TotalTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Rate.
        /// </summary>
        internal static string Stats_WinRate {
            get {
                return ResourceManager.GetString("Stats_WinRate", resourceCulture);
            }
        }
    }
}
